import { useEffect, useState } from "react";
import Image from "next/image";
import Head from "next/head";

import MainLayout from "@/layouts/MainLayout";
import PodcastsList from "@/components/podcastsList";
import { loadPodcasts } from "@/lib/loadPodcasts";
import { MagnifyingGlassIcon } from "@heroicons/react/20/solid";
import Loader from "@/components/loader";

export default function Home({ podcasts }) {
    const [dataApi, setDataApi] = useState([]);
    const [dataCount, setDataCount] = useState(0);
    const [valueForm, setValueForm] = useState("");
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        let res;
        setIsLoading(true);
        setDataApi(podcasts);
        setDataCount(podcasts.length);
        if (valueForm !== "") {
            res = podcasts.filter(
                (item) =>
                    item.title.label
                        .toLowerCase()
                        .includes(valueForm.toLowerCase()) ||
                    item["im:artist"].label
                        .toLowerCase()
                        .includes(valueForm.toLowerCase())
            );
            setDataCount(res.length > 0 && res.length);
        }
        setDataApi(res);
        setIsLoading(false);
    }, [podcasts, valueForm]);

    isLoading && <Loader />;

    return (
        <div>
            <Head>
                <title>Podcaster Apple</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <div className="flex flex-row justify-end items-center mt-10">
                    <span className="inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10 mr-5">
                        {dataCount}
                    </span>
                    <div className="relative rounded-full shadow-sm w-72">
                        <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-5">
                            <MagnifyingGlassIcon className="w-5 h-5 text-slate-500" />
                        </div>
                        <input
                            type="text"
                            name="searchTxt"
                            id="searchTxt"
                            onChange={(e) => setValueForm(e.target.value)}
                            className="border-neutral-100 block w-full py-3 rounded-full pl-12 focus:border-neutral-100 focus:ring-neutral-200 sm:text-sm"
                            placeholder="Busca por titulo o author"
                        />
                    </div>
                </div>
                <PodcastsList
                    data={
                        valueForm !== "" && dataApi?.length > 0
                            ? dataApi
                            : podcasts
                    }
                />
            </MainLayout>
        </div>
    );
}

export async function getStaticProps() {
    const podcasts = await loadPodcasts();
    return { props: { podcasts }, revalidate: 86400 };
}
