import Head from "next/head";
import { Header } from "@/components/header";

export default function MainLayout({ children }) {
    return (
        <div>
            <Head>
                <title>Podcaster Zara</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-white max-w-screen min-h-screen">
                <Header />
                <main className="max-w-6xl mx-auto">{children}</main>
            </div>
        </div>
    );
}
